### ISSUE TITLE
Roadmap for demo

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#1]
The project is just started and is still in the demo stage now.
The primary goal in this stage is to explore the possibility of our designs.

We plan to release the first demo in the next two months (2021.09 - 2021.10).
We are going to achieve the following objectives:

- [ ] A working demo with simple read/write APIs on AWS
- [ ] A report with statistics of the demo and other useful discoveries.
- [ ] Improve the design document according to lessens learned above.

However, we are short of hands.
If you think we are behind schedule, you can push us with a 👍

**Comment by huachaohuang** [comment]
Congratulations! We have finished this demo. Thank you for watching and participating in it!
For more details, please check [the report](https://engula.com/posts/demo-1/).
We will keep this issue open for a few days and welcome you to discuss the demo with us here.

**Comment by hi-wanghan** [comment]
Congrats! What's your plan on the networking stuff? Good news is the industry wholesale transit prices have fallen at least 50% during the past 8 years <though AWS is never part of it ;)>

**Comment by huachaohuang** [comment]
We may need some optimizations in the design and implementation.
Networking is not a blocker so far. It's only one piece of the big picture.

**Comment by tisonkun** [comment]
@huachaohuang you can link the post of demo 1 in the description https://engula.com/posts/demo-1/ .

Congrats! I'm reading it.

**Comment by tisonkun** [comment]
The first question I'd like to ask is that how can I reproduce your demo?

**Comment by huachaohuang** [comment]
@tisonkun Hmm, let me document it somewhere. But I have to say it is cumbersome since I haven't pay attention to the deployment stuff yet.
