### ISSUE TITLE
Roadmap 0.3

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#203]
Planned release date: Jan 28, 2022.

I don't have a clear plan for 0.3 yet. One possible goal is to provide a basic implementation of [Luna engine](https://github.com/engula/engula/discussions/195). Open for discussions.

- [ ] #235
- [ ] #229
- [ ] #228

**Comment by PatrickNicholas** [comment]
It seems that these APIs in Luna engine are sufficient for 0.3 yet.  In addition to providing a basic implementation, it also makes sense to make this implementation more solid and practical.

**Comment by huachaohuang** [comment]
@zojw seems working on the k8s and docker stuff, any thoughts?

**Comment by zojw** [comment]
> 

yup, I'm trying to do some investigation(learning k8s- -, write test code, and prepare design discussion) in a [local branch](https://github.com/zojw/engula/tree/v03-kube-2),  the mainly direction just follow [last online-meeting](https://github.com/engula/engula/discussions/182#discussioncomment-1785600)'s idea(boostrap kernel, then kernel boostrap & monitor & scale other components...)

current progress is... 

- [x] package docker image 
- [x] manager components as CustomResource
- [x] discovery component's address:port via API
- [ ] deploy or scale component via API
- [ ] another demo gRPC kernel deploy & discovery via API

[ ] still under investigation,  but it seems almost workable, and I will give a detailed discussion thread when the last two items are done(maybe this weekend or early next week), we need more k8s experts to help review

although there are many decisions & designs we need to take care & discuss, IMO we can finish those discussions and ship a k8s runnable in v0.3

**Comment by tisonkun** [comment]
@zojw could you start a discussion thread so that we can focus on implementing deployment? You can later create an issue with concrete items by ["Create issue from discussion"](https://github.com/github/feedback/discussions/2861#discussioncomment-696235). (Here is [an example](https://github.com/apache/skywalking/discussions/7756))

**Comment by tisonkun** [comment]
> One possible goal is to provide a basic implementation of Luna engine.

As mentioned in https://github.com/engula/engula/pull/266#issuecomment-1007467866,  the journal API is still unstable as described in #229 and #260. Also, the binary is broken now.

Do you still plan to deliver a basic implementation of Luna engine at Jan 28, 2022? Will it be a memory implementation, and used as a library only?

**Comment by huachaohuang** [comment]
I think regular releases are not suitable at the current stage for two reasons:

- It forces us to make a lot of temporary design and implementation to deliver things on time.
- Too many low-quality releases will be harmful to the image of the project and people will lose interest in us.

So I suggest that we think about that bigger picture described in https://github.com/engula/engula/discussions/245 first. We can come back to planned releases when we have a clearer path towards that goal. #252 #263 #260 #251 are some attempts to clear the path. I think I should start a new tracking issue for Engula 2022.

**Comment by tisonkun** [comment]
@huachaohuang totally agree! Before we have a clear picture, we can release when features are ready, i.e., a basically usable luna engine with deployment supports :)

Note: please update the PR description. We can still set up targets for a 0.3 release without an explicit deadline.

**Comment by huachaohuang** [comment]
Close this in favor of #270 for now. We can open a new issue for v0.3 when we have a clear estimation of the schedule.
