### ISSUE TITLE
Support Shared Journal

### ISSUE THREAD

**Issue by w41ter-l** [engula/engula#284]
This is a tracking issue for implementing the shard journal.

The design can be found in #280, #291.

# Prototype & Basic traits
- [x] #304
- [x] Add trait of shared journal: #283 
- [x] Add basic framework and structures: #285
- [x] #311 

# Phase 1

Target:
- Single replica, no replica fault dectector
- Support switch segment
- Support appending and reading events
- No electing
- No recovery
- In memory master & server

Tasks:
- [x] #325 
- [x] #326 
- [x] #327 
- [x] #328 
- [ ] Implement SegmentWriter
- [ ] Implement SegmentReader
- [ ] Implement `heartbeat` and switching segments
- [ ] Implement StreamWriter 
- [ ] Implement StreamReader
- [ ] Implement SharedJournal

# Phase 2

Target:
- Support electing
- Support recovery
- Multiple replica and NWR replication policy
- Replica fault detecting and replacing

Tasks: TODO

# Phase 3

Target:
- Master persistance
- Server persistance
- Archive to external storage

Tasks: TODO

**Comment by w41ter-l** [comment]
The task list currently only includes sub-tasks that focus on the skeleton of a shared journal; more sub-tasks must be added. I'll update and add the detail implementation as sub-tasks once the skeleton is complete.

**Comment by tisonkun** [comment]
@w41ter-l I think one of the subtask is bringing back grpc journal client & server - they are currently broken.

**Comment by tisonkun** [comment]
According to the discussion https://github.com/engula/engula/discussions/293#discussioncomment-2013238, you may think of what mapping engine:kernel is - 1:1 or n:1?

If engine always runs with kernel both in memory, the leader elections procedure may be different.
