### ISSUE TITLE
Implement  Cache Storage

### ISSUE THREAD

**Issue by zojw** [engula/engula#323]
ref #263 

Storage trait implements that combination of:  BaseStorage(S3Storage), LocalStorage(MemStorage)  and gRPCClientStorage(to another replica chains)

At last, CacheStorage itself should be exported as gRPC service as a gRPCStorage's server-side

## Phase 1

Support client put / read / list object in memory storage + s3 storage

  - [ ] Handle Put Object
     - [ ] Implement gRPC Server to request `BaseStorage` then `CacheStorage` if it's not replicate request, save CacheStorage if it's replicate request
     - [ ] Implement Storage Trait as CacheStorage to support request `MemStorage`(fs later) then `gRPCStorage` to follower
   - [ ] Handle ReadObject / ListObject / DeleteObject / CreateBucket / ListBucket / DeleteBucket in current local via 
   - [ ] Provide a CacheStorageServer binary = gRPC Storage Server  + Cache Storage { BaseStorage,  Multiple gRPC Client Storage}

## Phase 2

Support reconcile and HA logic that needed for current storage node, it should adopt with master reconcile logic

- [ ] Support reconcile logic in current node
  - As new added replica
  - As deleted replica
- [ ] Detect & clean up obsolete temp files

**Comment by zojw** [comment]
The shared storage development work has been migrated to another repo, the related issue has be replaced with https://github.com/zojw/shared-storage/issues/4, so close this first
