### ISSUE TITLE
Implement Remote storage client-side

### ISSUE THREAD

**Issue by zojw** [engula/engula#332]
## Phase 1

Support call reconfigured kernel without error handle

- [ ] Handle Put Object: Use `Discovery` client-side trait to find replicate cache nodes then request one of them(via gRPCStorage client-side trait)
- [ ] Handle Delete Object: Request Master Service in Kernel to delete object (via gRPCStorage trait backend for kernel)
- [ ] Handle Read Object:
  - [ ] Use `Discovery` client-side trait to find Cache Server Nodes and request read(in node local)
- [ ]  ListBucket, ListObject not sure is needed

## Phase 2

Support retry or hint master do refill

- [ ] Retry another cache node if report cache not found， finally request S3 (maybe need rate limit)
- [ ] Hint master server to reconcile and refill the cache

**Comment by zojw** [comment]
The shared storage development work has been migrated to another repo, the related issue has be replaced with https://github.com/zojw/shared-storage/issues/4, so close this first
