### ISSUE TITLE
Roadmap 0.4

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#490]
## Overview

Focus on the design and implementation of internal components. The planned release date is Apr 30, 2022.

## Project

- [ ] https://github.com/engula/engula/issues/504
- [x] #527

## Client

Support `I64`, `F64`, `Blob`, `Text`, `Map`, `Set`, and `List` data types.

- [x] #519
- [x] #584
- [x] #587
- [x] #597
- [x] #589
- [x] #600
- [x] #593
- [x] #595 
- [x] #602

## Kernel

- [x] #604
- [x] #609
- [x] #533
- [x] #611
- [x] #613
- [x] #614
- [ ] kernel/cooperator: handle f64 type expression
- [x] #617
- [ ] kernel/cooperator: handle text type expression
- [x] #621
- [ ] kernel/cooperator: handle set type expression
- [x] #619
- [x] #626
- [x] #628

## Stream Engine

Implement an embedded, persistent engine.

- [ ] #510 

## Object Engine

Implement an embedded, persistent engine.

- [x] #474 
- [x] #491
- [x] #494
- [x] #496
- [x] #498
- [x] #500
- [x] #508
- [x] #512
- [x] #546
- [x] #549
- [x] #552
- [x] #554
- [x] #559
- [x] #561
- [x] #563
- [x] #565
- [x] #567
- [x] #571
