### ISSUE TITLE
The Stream Engine 0.4

### ISSUE THREAD

**Issue by w41ter** [engula/engula#510]
# Overview

The goals of stream engine 0.4 are:
1. fully functional strem engine client
2. disk persistence store
3. in memory master, support simple scheduler

# Tasks 

## Migrate

- [x] #480 
- [x] #481 
- [x] #530
- [x] #523
- [x] #537

## Persistence Store

- [ ] #574
- [x] #631
- [x] #633
- [x] #634
- [x] #640
- [ ] #642

## Client

- [ ] stream-engine-client: support leader promoting to follower
- [ ] stream-engine-client: fix `StreamReader::try_next`
- [ ] #644
- [ ] stream-engine-client: `StreamReader::seek` support truncated stream
- [ ] stream-engine-client: support majority replication policy
- [ ] stream-engine-client: release useless memory in `Replicate::mem_store`

## Master 

- [x] #538
- [ ] #539
- [ ] #540
- [x] #541
- [ ] #542
- [ ] #543
- [ ] stream-engine-master: fix heartbeat response missing
- [ ] stream-engine-master: support replication policy configuration
- [ ] #646
- [ ] #645
