### ISSUE TITLE
Roadmap v0.2 - Storage

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#68]
Tasks:

- [x] Design document
- [x] Storage abstraction
- [x] A mem storage implementation
- [x] A file storage implementation
- [x] A grpc storage implementation

Most tasks have been done, but we still need to refactor some implementations before releasing v0.2.

**Comment by huachaohuang** [comment]
Reference: https://github.com/delta-io/delta-rs/tree/main/rust/src/storage

**Comment by huachaohuang** [comment]
AWS S3 performance guidelines: https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html

**Comment by huachaohuang** [comment]
@zojw Nice! I think you mean https://github.com/engula/engula/pull/86?

**Comment by zojw** [comment]
@huachaohuang emm....., it's my mistake, s/#68/#86/g 😄 

> I'd like to implement a prototype storage traits for aws-s3 & file system after #86 merged.

**Comment by huachaohuang** [comment]
@zojw You may be interested in https://github.com/tokio-rs/tokio-uring. There is no good support for asynchronous random file read so far, as you may need that when implementing the storage.

**Comment by huachaohuang** [comment]
I am going to implement a remote storage service now.

**Comment by tisonkun** [comment]
The ` A remote storage implementation` is finished and can be checked. I suggest @huachaohuang create a subtask issue the next time and let the PR close that subtask issue, which will automatically check the box and that's what GitHub provides.

**Comment by huachaohuang** [comment]
> The ` A remote storage implementation` is finished and can be checked. I suggest @huachaohuang create a subtask issue the next time and let the PR close that subtask issue, which will automatically check the box and that's what GitHub provides.

Actually, only the client part is finished. I think your suggestion makes sense. I will try to apply it. But it may not work well for me now, since the tasks are not so straightforward to be handled step by step so far. For example, I may rewrite a lot of things if necessary.

**Comment by zojw** [comment]
Hi, I'm trying to implement a storage trait for another local storage implement.

it will sit on `src/storage/fs` folder and the initial version should be a simple implementation:

1. user choose a disk path as base folder
2. create bucket as a secondary folder
3. each object saved as an object inside bucket folder

it's simple rough implements, we know real-world object storage has more complex implementations and handles complex detail, but we may not need a full-functional file system, so choose to start from simple and add more functionality as needed.

for code implement: it will choose using `tokio::fs`'s async operation as initial implement and supply `tokio-uring` as optional Object trait / ObjectUploader trait as replacements.

**Comment by huachaohuang** [comment]
@zojw sounds good to me. Go ahead.

**Comment by huachaohuang** [comment]
I think it's time to connect the storage and microunit modules. I am going to implement the unit traits for the grpc storage to see if we can deploy a storage unit.
