### ISSUE TITLE
Tracking issue for bootstrap server and client

### ISSUE THREAD

**Issue by w41ter** [engula/engula#704]
# Overview

The goals of current milestone:
1. fully functional client, router
2. cluster managerment (bootstrap, join)
3. admin (database, collection manager)

# Tasks

## Server Side

This section list server-related development works.

### Cluster

- [x] bootstrap cluster 
  - [x] #708
- [x] #711
  - [x] root group allocate a node id #718
- [x] root management
  - [x] #722
  - [x] #766
  - [x] #791
  - [x] #792
  - [x] #814
  - [x] #835

### Replica

- [x] replica management: depends on raft
  - [x] #728
  - [x] node liveness
  - [x] #726
  - [x] #742
  - [x] #743
  - [x] #744
  - [x] #758
  - [x] #759
  - [x] #762
  - [x] #823
  - [x] #836
- [x] replica commands
  - [x] #729
  - [x] #773
  - [x] #750
  - [x] #796
- [x] #808

### Raft

- [x] #719
  - server and transport
  - persist log and metadata
  - message forwarding and proposals replication
- [x] #756
- [x] #725
- [x] #757

### RPC and Service

- [x] #705
- [x] #706
- [x] #707
- [x] implement `Node` service
  - [x] implement `Node::Join`
  - [x] #730
  - [x] #714
  - [x] add `UpdateConfig` method to update group membership
- [x] implement `Root` service
  - [x] implement `Root::Admin`
    - [x] create database
    - [x] #745
  - [x] #748
  - [x] #746
  - [x] #812

## Client Side

This section list client-related development works.

### Client

- [x] #710
- [x] #721
- [x] #805

### Router

- [x] #765
- [x] #804

## Bin

- [x] #760
- [x] #761

**Comment by w41ter** [comment]
cc @huachaohuang @zojw @tisonkun
