### ISSUE TITLE
Tracking issues for bootstrap phase tests

### ISSUE THREAD

**Issue by w41ter** [engula/engula#846]
# Overview

This is the tracking issue for testing. At the same time records the bugs and required features found during testing.

Tests should be added as code, as long as the following conditions are met:
1. Stable and reproducible results
2. Easy to write and maintain
3. Short execution time.

# Tasks

- [x] functions
  - [x] boostrap cluster
  - [x] restart an shutdown cluster 
  - [x] promote root group to cluster
  - [x] create and apply snapshot
  - [x] recover from snapshot
  - [x] send and receives snapshot
  - [x] shard migration
  - [x] change configuration
  - [x] #874
  - [x] #869
- [x] cluster
  - [x] admin operations
    - [x] create collection
    - [x] create database
    - [x] add(x remove) node
  - [x] mutation/fetching operations
    - [x] basic operation
    - [x] #875
    - [x] #876
    - [x] #877
  - [x] shard migration
    - [x] #882
    - [x] #886
  - [x] schedule/balance
    - [x] group add(x remove)
    - [x] leader balance
    - [x] replica balance
    - [x] shard balance
  - [x] client router
    - [x] error response handling (node + root) #890，#900
    - [x] #884
    - [x] update cached router info (retry count) #857
- [ ] stability and fault tolerance
  - [ ] restart/die node
  - [ ] restart/die root leader
  - [ ] disk full
  - [ ] out of memory
  - [ ] disk backpress
  - [ ] network backpress
  - [ ] huge num of nodes(i.e. cpu/group)
  - [ ] huge num of shards(i.e. collection)
  - [ ] different group replica_num config

### Urgent

- [x] bugs
  - [x] #848
  - [ ] create a collection with 200 slots take 2-3 min
  - [x] #853
  - [x] #856
  - [x] #860
  - [x] #861
  - [x] #873
  - [x] #891
  - [x] #893
  - [x] #895 
  - [x] #896 
  - [x] #905
  - [x] #906
  - [x] #915
  - [x] #936 
  - [x] #938
  - [x] #939
  - [x] #943
  - [x] #954
  - [x] #972
  - [x] #990
  - [x] #999
  - [x] #1007 
  - [x] #1009
  - [x] #1016
  - [x] #1017
  - [x] #1019
  - [x] #1020
  - [x] #1023
  - [x] #1061
- [x] features
  - [x] #847
  - [x] #841
  - [x] #844 
  - [x] #864
  - [x] #865
  - [x] #868
  - [x] #967
  - [x] #976
  - [x] #977
  - [x] #992

### Normal

- [ ] bugs
  - [x] #855
  - [x] #889 
  - [x] #894
  - [x] #1002
  - [x] #903
  - [x] #920
  - [x] #923
  - [ ] #935 
  - [x] #948
  - [x] #949
  - [x] #950
  - [x] #952
  - [x] #956
  - [ ] #958
  - [ ] #965
  - [ ] #995
- [ ] features
  - [ ] #803 
  - [ ] root loop support graceful shutdown
  - [ ] #851
  - [x] #1002 
  - [ ] remove group
  - [ ] some missing features (maybe in next iterator)
    - [ ] persist balance step to survive between failures
    - [ ] take care of disk capacity in balance
    - [ ] take care of QPS / latency in balance
    - [ ] fine-grained handle replica role(e.g. non-voter)
    - [ ] healing duplicate balance operation caused by in-progressing & un-reported operation
    - [ ] balance speed control
    - [ ] handle create shard failure (rollback orphan shards)
  - [ ] replica commands
	- [ ] support inc (merge)
	- [ ] support condition_put(e.g. put_if_not_exist)
  - [x] #790
  - [x] #837
  - [x] #834
  - [x] #934 
  - [x] #918 
  - [x] #922

**Comment by w41ter** [comment]
Most of the features and bugs have been completed and fixed, now close this issue and move on to the next phase of tasks. The remaining unclosed issues are moved to the next stage.
